/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module adder(a, b, s);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  input [31:0] a;
  input [31:0] b;
  output [31:0] s;
  sky130_fd_sc_hd__xor2_1 _379_ (
    .A(_197_),
    .B(_165_),
    .X(_344_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _380_ (
    .A(_196_),
    .SLEEP(_164_),
    .X(_345_)
  );
  sky130_fd_sc_hd__nand2_1 _381_ (
    .A(_195_),
    .B(_163_),
    .Y(_346_)
  );
  sky130_fd_sc_hd__xnor2_1 _382_ (
    .A(_195_),
    .B(_163_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__and2_0 _383_ (
    .A(_194_),
    .B(_162_),
    .X(_225_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(_194_),
    .B(_162_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__and2_0 _385_ (
    .A(_193_),
    .B(_161_),
    .X(_227_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _386_ (
    .A(_193_),
    .SLEEP(_161_),
    .X(_228_)
  );
  sky130_fd_sc_hd__nand2b_1 _387_ (
    .A_N(_227_),
    .B(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _388_ (
    .A(_223_),
    .SLEEP(_191_),
    .X(_230_)
  );
  sky130_fd_sc_hd__nand2_1 _389_ (
    .A(_223_),
    .B(_191_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(_222_),
    .B(_190_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xnor2_1 _391_ (
    .A(_222_),
    .B(_190_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__and2_0 _392_ (
    .A(_221_),
    .B(_189_),
    .X(_234_)
  );
  sky130_fd_sc_hd__nor2_1 _393_ (
    .A(_221_),
    .B(_189_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__and2_0 _394_ (
    .A(_220_),
    .B(_188_),
    .X(_236_)
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(_220_),
    .B(_188_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nor2_1 _396_ (
    .A(_236_),
    .B(_237_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nand2_1 _397_ (
    .A(_219_),
    .B(_187_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _398_ (
    .A(_219_),
    .SLEEP(_187_),
    .X(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _399_ (
    .A(_218_),
    .B(_186_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__xnor2_1 _400_ (
    .A(_218_),
    .B(_186_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__and2_0 _401_ (
    .A(_217_),
    .B(_185_),
    .X(_243_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(_217_),
    .B(_185_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__and2_0 _403_ (
    .A(_214_),
    .B(_182_),
    .X(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _404_ (
    .A(_203_),
    .B(_171_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand2_1 _405_ (
    .A(_192_),
    .B(_160_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(_203_),
    .B(_171_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _407_ (
    .A(_246_),
    .SLEEP(_248_),
    .X(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _408_ (
    .A1(_247_),
    .A2(_248_),
    .B1(_246_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor2_1 _409_ (
    .A(_214_),
    .B(_182_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(_245_),
    .B(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__a21oi_1 _411_ (
    .A1(_250_),
    .A2(_252_),
    .B1(_245_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a211oi_1 _412_ (
    .A1(_250_),
    .A2(_252_),
    .B1(_243_),
    .C1(_245_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nor3_1 _413_ (
    .A(_242_),
    .B(_244_),
    .C(_254_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__o31ai_1 _414_ (
    .A1(_242_),
    .A2(_244_),
    .A3(_254_),
    .B1(_241_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__o311ai_0 _415_ (
    .A1(_242_),
    .A2(_244_),
    .A3(_254_),
    .B1(_241_),
    .C1(_239_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nand3_1 _416_ (
    .A(_238_),
    .B(_240_),
    .C(_257_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__a31oi_1 _417_ (
    .A1(_238_),
    .A2(_240_),
    .A3(_257_),
    .B1(_236_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__a311oi_1 _418_ (
    .A1(_238_),
    .A2(_240_),
    .A3(_257_),
    .B1(_236_),
    .C1(_234_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _419_ (
    .A(_235_),
    .B(_260_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__o31ai_1 _420_ (
    .A1(_233_),
    .A2(_235_),
    .A3(_260_),
    .B1(_232_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__o311ai_0 _421_ (
    .A1(_233_),
    .A2(_235_),
    .A3(_260_),
    .B1(_232_),
    .C1(_231_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__and2_0 _422_ (
    .A(_230_),
    .B(_263_),
    .X(_264_)
  );
  sky130_fd_sc_hd__a21oi_1 _423_ (
    .A1(_228_),
    .A2(_264_),
    .B1(_227_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__a311oi_1 _424_ (
    .A1(_228_),
    .A2(_230_),
    .A3(_263_),
    .B1(_227_),
    .C1(_225_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nor3_1 _425_ (
    .A(_224_),
    .B(_226_),
    .C(_266_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(_196_),
    .B(_164_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__o311ai_0 _427_ (
    .A1(_224_),
    .A2(_226_),
    .A3(_266_),
    .B1(_268_),
    .C1(_346_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nand2_1 _428_ (
    .A(_345_),
    .B(_268_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(_345_),
    .B(_269_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__xnor2_1 _430_ (
    .A(_344_),
    .B(_271_),
    .Y(_352_)
  );
  sky130_fd_sc_hd__a32oi_1 _431_ (
    .A1(_344_),
    .A2(_345_),
    .A3(_269_),
    .B1(_165_),
    .B2(_197_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor2_1 _432_ (
    .A(_198_),
    .B(_166_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__xor2_1 _433_ (
    .A(_198_),
    .B(_166_),
    .X(_274_)
  );
  sky130_fd_sc_hd__xnor2_1 _434_ (
    .A(_272_),
    .B(_274_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__nand2_1 _435_ (
    .A(_199_),
    .B(_167_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(_199_),
    .B(_167_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _437_ (
    .A(_275_),
    .SLEEP(_276_),
    .X(_277_)
  );
  sky130_fd_sc_hd__a22oi_1 _438_ (
    .A1(_197_),
    .A2(_165_),
    .B1(_198_),
    .B2(_166_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__clkinv_1 _439_ (
    .A(_278_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__a31oi_1 _440_ (
    .A1(_344_),
    .A2(_345_),
    .A3(_269_),
    .B1(_279_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(_273_),
    .B(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__nand2_1 _442_ (
    .A(_277_),
    .B(_281_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__xor2_1 _443_ (
    .A(_277_),
    .B(_281_),
    .X(_354_)
  );
  sky130_fd_sc_hd__nand2_1 _444_ (
    .A(_275_),
    .B(_282_),
    .Y(_283_)
  );
  sky130_fd_sc_hd__nand2_1 _445_ (
    .A(_200_),
    .B(_168_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _446_ (
    .A(_200_),
    .SLEEP(_168_),
    .X(_285_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(_284_),
    .B(_285_),
    .Y(_286_)
  );
  sky130_fd_sc_hd__xnor2_1 _448_ (
    .A(_283_),
    .B(_286_),
    .Y(_355_)
  );
  sky130_fd_sc_hd__and2_0 _449_ (
    .A(_201_),
    .B(_169_),
    .X(_287_)
  );
  sky130_fd_sc_hd__nor2_1 _450_ (
    .A(_201_),
    .B(_169_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__nor2_1 _451_ (
    .A(_287_),
    .B(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__o311ai_0 _452_ (
    .A1(_273_),
    .A2(_276_),
    .A3(_280_),
    .B1(_284_),
    .C1(_275_),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand2_1 _453_ (
    .A(_285_),
    .B(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__xnor2_1 _454_ (
    .A(_289_),
    .B(_291_),
    .Y(_356_)
  );
  sky130_fd_sc_hd__a31oi_1 _455_ (
    .A1(_285_),
    .A2(_289_),
    .A3(_290_),
    .B1(_287_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__and2_0 _456_ (
    .A(_202_),
    .B(_170_),
    .X(_293_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_202_),
    .B(_170_),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nor2_1 _458_ (
    .A(_293_),
    .B(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__xnor2_1 _459_ (
    .A(_292_),
    .B(_295_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(_204_),
    .B(_172_),
    .Y(_296_)
  );
  sky130_fd_sc_hd__xnor2_1 _461_ (
    .A(_204_),
    .B(_172_),
    .Y(_297_)
  );
  sky130_fd_sc_hd__a311oi_1 _462_ (
    .A1(_285_),
    .A2(_289_),
    .A3(_290_),
    .B1(_293_),
    .C1(_287_),
    .Y(_298_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _463_ (
    .A(_294_),
    .SLEEP(_298_),
    .X(_299_)
  );
  sky130_fd_sc_hd__xor2_1 _464_ (
    .A(_297_),
    .B(_299_),
    .X(_359_)
  );
  sky130_fd_sc_hd__o21ai_0 _465_ (
    .A1(_297_),
    .A2(_299_),
    .B1(_296_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(_205_),
    .B(_173_),
    .Y(_301_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(_205_),
    .B(_173_),
    .Y(_302_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _468_ (
    .A(_301_),
    .SLEEP(_302_),
    .X(_303_)
  );
  sky130_fd_sc_hd__xor2_1 _469_ (
    .A(_300_),
    .B(_303_),
    .X(_360_)
  );
  sky130_fd_sc_hd__nand2_1 _470_ (
    .A(_206_),
    .B(_174_),
    .Y(_304_)
  );
  sky130_fd_sc_hd__xnor2_1 _471_ (
    .A(_206_),
    .B(_174_),
    .Y(_305_)
  );
  sky130_fd_sc_hd__o311a_1 _472_ (
    .A1(_294_),
    .A2(_297_),
    .A3(_298_),
    .B1(_301_),
    .C1(_296_),
    .X(_306_)
  );
  sky130_fd_sc_hd__nor2_1 _473_ (
    .A(_302_),
    .B(_306_),
    .Y(_307_)
  );
  sky130_fd_sc_hd__xnor2_1 _474_ (
    .A(_305_),
    .B(_307_),
    .Y(_361_)
  );
  sky130_fd_sc_hd__o31ai_1 _475_ (
    .A1(_302_),
    .A2(_305_),
    .A3(_306_),
    .B1(_304_),
    .Y(_308_)
  );
  sky130_fd_sc_hd__nand2_1 _476_ (
    .A(_207_),
    .B(_175_),
    .Y(_309_)
  );
  sky130_fd_sc_hd__nor2_1 _477_ (
    .A(_207_),
    .B(_175_),
    .Y(_310_)
  );
  sky130_fd_sc_hd__xnor2_1 _478_ (
    .A(_207_),
    .B(_175_),
    .Y(_311_)
  );
  sky130_fd_sc_hd__xnor2_1 _479_ (
    .A(_308_),
    .B(_311_),
    .Y(_362_)
  );
  sky130_fd_sc_hd__nand2_1 _480_ (
    .A(_208_),
    .B(_176_),
    .Y(_312_)
  );
  sky130_fd_sc_hd__xnor2_1 _481_ (
    .A(_208_),
    .B(_176_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o311a_1 _482_ (
    .A1(_302_),
    .A2(_305_),
    .A3(_306_),
    .B1(_309_),
    .C1(_304_),
    .X(_314_)
  );
  sky130_fd_sc_hd__nor2_1 _483_ (
    .A(_310_),
    .B(_314_),
    .Y(_315_)
  );
  sky130_fd_sc_hd__xnor2_1 _484_ (
    .A(_313_),
    .B(_315_),
    .Y(_363_)
  );
  sky130_fd_sc_hd__o31ai_1 _485_ (
    .A1(_310_),
    .A2(_313_),
    .A3(_314_),
    .B1(_312_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__xnor2_1 _486_ (
    .A(_209_),
    .B(_177_),
    .Y(_317_)
  );
  sky130_fd_sc_hd__xnor2_1 _487_ (
    .A(_316_),
    .B(_317_),
    .Y(_364_)
  );
  sky130_fd_sc_hd__maj3_1 _488_ (
    .A(_209_),
    .B(_177_),
    .C(_316_),
    .X(_318_)
  );
  sky130_fd_sc_hd__and2_0 _489_ (
    .A(_210_),
    .B(_178_),
    .X(_319_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(_210_),
    .B(_178_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__nor2_1 _491_ (
    .A(_319_),
    .B(_320_),
    .Y(_321_)
  );
  sky130_fd_sc_hd__xor2_1 _492_ (
    .A(_318_),
    .B(_321_),
    .X(_365_)
  );
  sky130_fd_sc_hd__a21oi_1 _493_ (
    .A1(_318_),
    .A2(_321_),
    .B1(_319_),
    .Y(_322_)
  );
  sky130_fd_sc_hd__nor2_1 _494_ (
    .A(_211_),
    .B(_179_),
    .Y(_323_)
  );
  sky130_fd_sc_hd__xor2_1 _495_ (
    .A(_211_),
    .B(_179_),
    .X(_324_)
  );
  sky130_fd_sc_hd__xnor2_1 _496_ (
    .A(_322_),
    .B(_324_),
    .Y(_366_)
  );
  sky130_fd_sc_hd__nand2_1 _497_ (
    .A(_212_),
    .B(_180_),
    .Y(_325_)
  );
  sky130_fd_sc_hd__xnor2_1 _498_ (
    .A(_212_),
    .B(_180_),
    .Y(_326_)
  );
  sky130_fd_sc_hd__a221oi_1 _499_ (
    .A1(_211_),
    .A2(_179_),
    .B1(_318_),
    .B2(_321_),
    .C1(_319_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__nor2_1 _500_ (
    .A(_323_),
    .B(_327_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__xnor2_1 _501_ (
    .A(_326_),
    .B(_328_),
    .Y(_367_)
  );
  sky130_fd_sc_hd__o31ai_1 _502_ (
    .A1(_323_),
    .A2(_326_),
    .A3(_327_),
    .B1(_325_),
    .Y(_329_)
  );
  sky130_fd_sc_hd__xnor2_1 _503_ (
    .A(_213_),
    .B(_181_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__xnor2_1 _504_ (
    .A(_329_),
    .B(_330_),
    .Y(_368_)
  );
  sky130_fd_sc_hd__maj3_1 _505_ (
    .A(_213_),
    .B(_181_),
    .C(_329_),
    .X(_331_)
  );
  sky130_fd_sc_hd__xnor2_1 _506_ (
    .A(_215_),
    .B(_183_),
    .Y(_332_)
  );
  sky130_fd_sc_hd__xnor2_1 _507_ (
    .A(_331_),
    .B(_332_),
    .Y(_370_)
  );
  sky130_fd_sc_hd__maj3_1 _508_ (
    .A(_215_),
    .B(_183_),
    .C(_331_),
    .X(_333_)
  );
  sky130_fd_sc_hd__xnor2_1 _509_ (
    .A(_216_),
    .B(_184_),
    .Y(_334_)
  );
  sky130_fd_sc_hd__xnor2_1 _510_ (
    .A(_333_),
    .B(_334_),
    .Y(_371_)
  );
  sky130_fd_sc_hd__xor2_1 _511_ (
    .A(_192_),
    .B(_160_),
    .X(_347_)
  );
  sky130_fd_sc_hd__xnor2_1 _512_ (
    .A(_247_),
    .B(_249_),
    .Y(_358_)
  );
  sky130_fd_sc_hd__xor2_1 _513_ (
    .A(_250_),
    .B(_252_),
    .X(_369_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _514_ (
    .A(_243_),
    .SLEEP(_244_),
    .X(_335_)
  );
  sky130_fd_sc_hd__xor2_1 _515_ (
    .A(_253_),
    .B(_335_),
    .X(_372_)
  );
  sky130_fd_sc_hd__o21ai_0 _516_ (
    .A1(_244_),
    .A2(_254_),
    .B1(_242_),
    .Y(_336_)
  );
  sky130_fd_sc_hd__nor2b_1 _517_ (
    .A(_255_),
    .B_N(_336_),
    .Y(_373_)
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(_239_),
    .B(_240_),
    .Y(_337_)
  );
  sky130_fd_sc_hd__xnor2_1 _519_ (
    .A(_256_),
    .B(_337_),
    .Y(_374_)
  );
  sky130_fd_sc_hd__a21oi_1 _520_ (
    .A1(_240_),
    .A2(_257_),
    .B1(_238_),
    .Y(_338_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _521_ (
    .A(_258_),
    .SLEEP(_338_),
    .X(_375_)
  );
  sky130_fd_sc_hd__nor2_1 _522_ (
    .A(_234_),
    .B(_235_),
    .Y(_339_)
  );
  sky130_fd_sc_hd__xnor2_1 _523_ (
    .A(_259_),
    .B(_339_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__xnor2_1 _524_ (
    .A(_233_),
    .B(_261_),
    .Y(_377_)
  );
  sky130_fd_sc_hd__nand2_1 _525_ (
    .A(_230_),
    .B(_231_),
    .Y(_340_)
  );
  sky130_fd_sc_hd__xnor2_1 _526_ (
    .A(_262_),
    .B(_340_),
    .Y(_378_)
  );
  sky130_fd_sc_hd__xnor2_1 _527_ (
    .A(_229_),
    .B(_264_),
    .Y(_348_)
  );
  sky130_fd_sc_hd__nor2_1 _528_ (
    .A(_225_),
    .B(_226_),
    .Y(_341_)
  );
  sky130_fd_sc_hd__xnor2_1 _529_ (
    .A(_265_),
    .B(_341_),
    .Y(_349_)
  );
  sky130_fd_sc_hd__o21a_1 _530_ (
    .A1(_226_),
    .A2(_266_),
    .B1(_224_),
    .X(_342_)
  );
  sky130_fd_sc_hd__nor2_1 _531_ (
    .A(_267_),
    .B(_342_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__a21oi_1 _532_ (
    .A1(_195_),
    .A2(_163_),
    .B1(_267_),
    .Y(_343_)
  );
  sky130_fd_sc_hd__xor2_1 _533_ (
    .A(_270_),
    .B(_343_),
    .X(_351_)
  );
  assign _197_ = b[14];
  assign _165_ = a[14];
  assign _196_ = b[13];
  assign _164_ = a[13];
  assign _195_ = b[12];
  assign _163_ = a[12];
  assign _194_ = b[11];
  assign _162_ = a[11];
  assign _193_ = b[10];
  assign _161_ = a[10];
  assign _223_ = b[9];
  assign _191_ = a[9];
  assign _222_ = b[8];
  assign _190_ = a[8];
  assign _221_ = b[7];
  assign _189_ = a[7];
  assign _220_ = b[6];
  assign _188_ = a[6];
  assign _219_ = b[5];
  assign _187_ = a[5];
  assign _218_ = b[4];
  assign _186_ = a[4];
  assign _217_ = b[3];
  assign _185_ = a[3];
  assign _214_ = b[2];
  assign _182_ = a[2];
  assign _203_ = b[1];
  assign _171_ = a[1];
  assign _192_ = b[0];
  assign _160_ = a[0];
  assign s[14] = _352_;
  assign _198_ = b[15];
  assign _166_ = a[15];
  assign s[15] = _353_;
  assign _199_ = b[16];
  assign _167_ = a[16];
  assign s[16] = _354_;
  assign _200_ = b[17];
  assign _168_ = a[17];
  assign s[17] = _355_;
  assign _201_ = b[18];
  assign _169_ = a[18];
  assign s[18] = _356_;
  assign _202_ = b[19];
  assign _170_ = a[19];
  assign s[19] = _357_;
  assign _204_ = b[20];
  assign _172_ = a[20];
  assign s[20] = _359_;
  assign _205_ = b[21];
  assign _173_ = a[21];
  assign s[21] = _360_;
  assign _206_ = b[22];
  assign _174_ = a[22];
  assign s[22] = _361_;
  assign _207_ = b[23];
  assign _175_ = a[23];
  assign s[23] = _362_;
  assign _208_ = b[24];
  assign _176_ = a[24];
  assign s[24] = _363_;
  assign _209_ = b[25];
  assign _177_ = a[25];
  assign s[25] = _364_;
  assign _210_ = b[26];
  assign _178_ = a[26];
  assign s[26] = _365_;
  assign _211_ = b[27];
  assign _179_ = a[27];
  assign s[27] = _366_;
  assign _212_ = b[28];
  assign _180_ = a[28];
  assign s[28] = _367_;
  assign _213_ = b[29];
  assign _181_ = a[29];
  assign s[29] = _368_;
  assign _215_ = b[30];
  assign _183_ = a[30];
  assign s[30] = _370_;
  assign _216_ = b[31];
  assign _184_ = a[31];
  assign s[31] = _371_;
  assign s[0] = _347_;
  assign s[1] = _358_;
  assign s[2] = _369_;
  assign s[3] = _372_;
  assign s[4] = _373_;
  assign s[5] = _374_;
  assign s[6] = _375_;
  assign s[7] = _376_;
  assign s[8] = _377_;
  assign s[9] = _378_;
  assign s[10] = _348_;
  assign s[11] = _349_;
  assign s[12] = _350_;
  assign s[13] = _351_;
endmodule
