/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module and2(a, b, y);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  input [31:0] a;
  input [31:0] b;
  output [31:0] y;
  sky130_fd_sc_hd__and2_0 _096_ (
    .A(_045_),
    .B(_013_),
    .X(_077_)
  );
  sky130_fd_sc_hd__and2_0 _097_ (
    .A(_046_),
    .B(_014_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and2_0 _098_ (
    .A(_047_),
    .B(_015_),
    .X(_079_)
  );
  sky130_fd_sc_hd__and2_0 _099_ (
    .A(_048_),
    .B(_016_),
    .X(_080_)
  );
  sky130_fd_sc_hd__and2_0 _100_ (
    .A(_049_),
    .B(_017_),
    .X(_081_)
  );
  sky130_fd_sc_hd__and2_0 _101_ (
    .A(_050_),
    .B(_018_),
    .X(_082_)
  );
  sky130_fd_sc_hd__and2_0 _102_ (
    .A(_051_),
    .B(_019_),
    .X(_083_)
  );
  sky130_fd_sc_hd__and2_0 _103_ (
    .A(_052_),
    .B(_020_),
    .X(_084_)
  );
  sky130_fd_sc_hd__and2_0 _104_ (
    .A(_053_),
    .B(_021_),
    .X(_085_)
  );
  sky130_fd_sc_hd__and2_0 _105_ (
    .A(_055_),
    .B(_023_),
    .X(_087_)
  );
  sky130_fd_sc_hd__and2_0 _106_ (
    .A(_056_),
    .B(_024_),
    .X(_088_)
  );
  sky130_fd_sc_hd__and2_0 _107_ (
    .A(_032_),
    .B(_000_),
    .X(_064_)
  );
  sky130_fd_sc_hd__and2_0 _108_ (
    .A(_043_),
    .B(_011_),
    .X(_075_)
  );
  sky130_fd_sc_hd__and2_0 _109_ (
    .A(_054_),
    .B(_022_),
    .X(_086_)
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(_057_),
    .B(_025_),
    .X(_089_)
  );
  sky130_fd_sc_hd__and2_0 _111_ (
    .A(_058_),
    .B(_026_),
    .X(_090_)
  );
  sky130_fd_sc_hd__and2_0 _112_ (
    .A(_059_),
    .B(_027_),
    .X(_091_)
  );
  sky130_fd_sc_hd__and2_0 _113_ (
    .A(_060_),
    .B(_028_),
    .X(_092_)
  );
  sky130_fd_sc_hd__and2_0 _114_ (
    .A(_061_),
    .B(_029_),
    .X(_093_)
  );
  sky130_fd_sc_hd__and2_0 _115_ (
    .A(_062_),
    .B(_030_),
    .X(_094_)
  );
  sky130_fd_sc_hd__and2_0 _116_ (
    .A(_063_),
    .B(_031_),
    .X(_095_)
  );
  sky130_fd_sc_hd__and2_0 _117_ (
    .A(_033_),
    .B(_001_),
    .X(_065_)
  );
  sky130_fd_sc_hd__and2_0 _118_ (
    .A(_034_),
    .B(_002_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and2_0 _119_ (
    .A(_035_),
    .B(_003_),
    .X(_067_)
  );
  sky130_fd_sc_hd__and2_0 _120_ (
    .A(_036_),
    .B(_004_),
    .X(_068_)
  );
  sky130_fd_sc_hd__and2_0 _121_ (
    .A(_037_),
    .B(_005_),
    .X(_069_)
  );
  sky130_fd_sc_hd__and2_0 _122_ (
    .A(_038_),
    .B(_006_),
    .X(_070_)
  );
  sky130_fd_sc_hd__and2_0 _123_ (
    .A(_039_),
    .B(_007_),
    .X(_071_)
  );
  sky130_fd_sc_hd__and2_0 _124_ (
    .A(_040_),
    .B(_008_),
    .X(_072_)
  );
  sky130_fd_sc_hd__and2_0 _125_ (
    .A(_041_),
    .B(_009_),
    .X(_073_)
  );
  sky130_fd_sc_hd__and2_0 _126_ (
    .A(_042_),
    .B(_010_),
    .X(_074_)
  );
  sky130_fd_sc_hd__and2_0 _127_ (
    .A(_044_),
    .B(_012_),
    .X(_076_)
  );
  assign _045_ = b[21];
  assign _013_ = a[21];
  assign y[21] = _077_;
  assign _046_ = b[22];
  assign _014_ = a[22];
  assign y[22] = _078_;
  assign _047_ = b[23];
  assign _015_ = a[23];
  assign y[23] = _079_;
  assign _048_ = b[24];
  assign _016_ = a[24];
  assign y[24] = _080_;
  assign _049_ = b[25];
  assign _017_ = a[25];
  assign y[25] = _081_;
  assign _050_ = b[26];
  assign _018_ = a[26];
  assign y[26] = _082_;
  assign _051_ = b[27];
  assign _019_ = a[27];
  assign y[27] = _083_;
  assign _052_ = b[28];
  assign _020_ = a[28];
  assign y[28] = _084_;
  assign _053_ = b[29];
  assign _021_ = a[29];
  assign y[29] = _085_;
  assign _055_ = b[30];
  assign _023_ = a[30];
  assign y[30] = _087_;
  assign _056_ = b[31];
  assign _024_ = a[31];
  assign y[31] = _088_;
  assign _032_ = b[0];
  assign _000_ = a[0];
  assign y[0] = _064_;
  assign _043_ = b[1];
  assign _011_ = a[1];
  assign y[1] = _075_;
  assign _054_ = b[2];
  assign _022_ = a[2];
  assign y[2] = _086_;
  assign _057_ = b[3];
  assign _025_ = a[3];
  assign y[3] = _089_;
  assign _058_ = b[4];
  assign _026_ = a[4];
  assign y[4] = _090_;
  assign _059_ = b[5];
  assign _027_ = a[5];
  assign y[5] = _091_;
  assign _060_ = b[6];
  assign _028_ = a[6];
  assign y[6] = _092_;
  assign _061_ = b[7];
  assign _029_ = a[7];
  assign y[7] = _093_;
  assign _062_ = b[8];
  assign _030_ = a[8];
  assign y[8] = _094_;
  assign _063_ = b[9];
  assign _031_ = a[9];
  assign y[9] = _095_;
  assign _033_ = b[10];
  assign _001_ = a[10];
  assign y[10] = _065_;
  assign _034_ = b[11];
  assign _002_ = a[11];
  assign y[11] = _066_;
  assign _035_ = b[12];
  assign _003_ = a[12];
  assign y[12] = _067_;
  assign _036_ = b[13];
  assign _004_ = a[13];
  assign y[13] = _068_;
  assign _037_ = b[14];
  assign _005_ = a[14];
  assign y[14] = _069_;
  assign _038_ = b[15];
  assign _006_ = a[15];
  assign y[15] = _070_;
  assign _039_ = b[16];
  assign _007_ = a[16];
  assign y[16] = _071_;
  assign _040_ = b[17];
  assign _008_ = a[17];
  assign y[17] = _072_;
  assign _041_ = b[18];
  assign _009_ = a[18];
  assign y[18] = _073_;
  assign _042_ = b[19];
  assign _010_ = a[19];
  assign y[19] = _074_;
  assign _044_ = b[20];
  assign _012_ = a[20];
  assign y[20] = _076_;
endmodule
