/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module branchCtrl(bCtrl, r1, r2, bSel);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  input [2:0] bCtrl;
  output bSel;
  input [31:0] r1;
  input [31:0] r2;
  sky130_fd_sc_hd__clkinv_1 _347_ (
    .A(_306_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(_336_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__clkinv_1 _349_ (
    .A(_335_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(_334_),
    .Y(_255_)
  );
  sky130_fd_sc_hd__clkinv_1 _351_ (
    .A(_299_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__clkinv_1 _352_ (
    .A(_298_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__clkinv_1 _353_ (
    .A(_328_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__clkinv_1 _354_ (
    .A(_327_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__clkinv_1 _355_ (
    .A(_325_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(_323_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(_321_),
    .Y(_262_)
  );
  sky130_fd_sc_hd__clkinv_1 _358_ (
    .A(_287_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__clkinv_1 _359_ (
    .A(_286_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(_317_),
    .Y(_265_)
  );
  sky130_fd_sc_hd__clkinv_1 _361_ (
    .A(_346_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__clkinv_1 _362_ (
    .A(_313_),
    .Y(_267_)
  );
  sky130_fd_sc_hd__clkinv_1 _363_ (
    .A(_344_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__clkinv_1 _364_ (
    .A(_342_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__clkinv_1 _365_ (
    .A(_341_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__clkinv_1 _366_ (
    .A(_337_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__clkinv_1 _367_ (
    .A(_326_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__clkinv_1 _368_ (
    .A(_283_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__clkinv_1 _369_ (
    .A(_151_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _370_ (
    .A(_339_),
    .SLEEP(_307_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nand2b_1 _371_ (
    .A_N(_339_),
    .B(_307_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__xor2_1 _372_ (
    .A(_298_),
    .B(_330_),
    .X(_277_)
  );
  sky130_fd_sc_hd__nand2b_1 _373_ (
    .A_N(_329_),
    .B(_297_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__xor2_1 _374_ (
    .A(_297_),
    .B(_329_),
    .X(_279_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _375_ (
    .A(_328_),
    .SLEEP(_296_),
    .X(_280_)
  );
  sky130_fd_sc_hd__nor3_1 _376_ (
    .A(_277_),
    .B(_279_),
    .C(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__or3_1 _377_ (
    .A(_277_),
    .B(_279_),
    .C(_280_),
    .X(_282_)
  );
  sky130_fd_sc_hd__a22oi_1 _378_ (
    .A1(_296_),
    .A2(_258_),
    .B1(_295_),
    .B2(_259_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__o211ai_1 _379_ (
    .A1(_295_),
    .A2(_259_),
    .B1(_281_),
    .C1(_155_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2b_1 _380_ (
    .A_N(_331_),
    .B(_299_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2b_1 _381_ (
    .A_N(_332_),
    .B(_300_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(_157_),
    .B(_158_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _383_ (
    .A(_301_),
    .SLEEP(_333_),
    .X(_160_)
  );
  sky130_fd_sc_hd__o22ai_1 _384_ (
    .A1(_304_),
    .A2(_253_),
    .B1(_303_),
    .B2(_254_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _385_ (
    .A(_303_),
    .SLEEP(_335_),
    .X(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _386_ (
    .A1(_302_),
    .A2(_255_),
    .B1(_162_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__o21ai_0 _387_ (
    .A1(_252_),
    .A2(_338_),
    .B1(_276_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a211oi_1 _388_ (
    .A1(_252_),
    .A2(_338_),
    .B1(_275_),
    .C1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _389_ (
    .A(_304_),
    .SLEEP(_336_),
    .X(_166_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _390_ (
    .A(_333_),
    .SLEEP(_301_),
    .X(_167_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _391_ (
    .A(_332_),
    .SLEEP(_300_),
    .X(_168_)
  );
  sky130_fd_sc_hd__a2111oi_0 _392_ (
    .A1(_256_),
    .A2(_331_),
    .B1(_160_),
    .C1(_166_),
    .D1(_167_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _393_ (
    .A(_162_),
    .SLEEP(_168_),
    .X(_170_)
  );
  sky130_fd_sc_hd__xor2_1 _394_ (
    .A(_302_),
    .B(_334_),
    .X(_171_)
  );
  sky130_fd_sc_hd__nor4_1 _395_ (
    .A(_159_),
    .B(_161_),
    .C(_170_),
    .D(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__and3_1 _396_ (
    .A(_165_),
    .B(_169_),
    .C(_172_),
    .X(_173_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _397_ (
    .A(_292_),
    .SLEEP(_324_),
    .X(_174_)
  );
  sky130_fd_sc_hd__xor2_1 _398_ (
    .A(_292_),
    .B(_324_),
    .X(_175_)
  );
  sky130_fd_sc_hd__xor2_1 _399_ (
    .A(_293_),
    .B(_325_),
    .X(_176_)
  );
  sky130_fd_sc_hd__nor2_1 _400_ (
    .A(_175_),
    .B(_176_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _401_ (
    .A(_290_),
    .SLEEP(_322_),
    .X(_178_)
  );
  sky130_fd_sc_hd__xnor2_1 _402_ (
    .A(_290_),
    .B(_322_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__xor2_1 _403_ (
    .A(_291_),
    .B(_323_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nor4_1 _404_ (
    .A(_156_),
    .B(_175_),
    .C(_176_),
    .D(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nand3_1 _405_ (
    .A(_173_),
    .B(_179_),
    .C(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _406_ (
    .A(_288_),
    .SLEEP(_320_),
    .X(_183_)
  );
  sky130_fd_sc_hd__xor2_1 _407_ (
    .A(_288_),
    .B(_320_),
    .X(_184_)
  );
  sky130_fd_sc_hd__xor2_1 _408_ (
    .A(_289_),
    .B(_321_),
    .X(_185_)
  );
  sky130_fd_sc_hd__a211oi_1 _409_ (
    .A1(_263_),
    .A2(_319_),
    .B1(_184_),
    .C1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__o22ai_1 _410_ (
    .A1(_263_),
    .A2(_319_),
    .B1(_264_),
    .B2(_318_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _411_ (
    .A(_318_),
    .SLEEP(_286_),
    .X(_188_)
  );
  sky130_fd_sc_hd__nor3b_1 _412_ (
    .A(_188_),
    .B(_187_),
    .C_N(_186_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _413_ (
    .A(_284_),
    .SLEEP(_316_),
    .X(_190_)
  );
  sky130_fd_sc_hd__xnor2_1 _414_ (
    .A(_284_),
    .B(_316_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__xnor2_1 _415_ (
    .A(_285_),
    .B(_317_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _416_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _417_ (
    .A1_N(_345_),
    .A2_N(_267_),
    .B1(_266_),
    .B2(_314_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor2_1 _418_ (
    .A(_314_),
    .B(_266_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__a21oi_1 _419_ (
    .A1(_267_),
    .A2(_345_),
    .B1(_193_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__and4b_1 _420_ (
    .A_N(_195_),
    .B(_196_),
    .C(_189_),
    .D(_194_),
    .X(_197_)
  );
  sky130_fd_sc_hd__xor2_1 _421_ (
    .A(_294_),
    .B(_326_),
    .X(_198_)
  );
  sky130_fd_sc_hd__a21oi_1 _422_ (
    .A1(_273_),
    .A2(_315_),
    .B1(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _423_ (
    .A1(_294_),
    .A2(_272_),
    .B1(_199_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _424_ (
    .A(_311_),
    .SLEEP(_343_),
    .X(_201_)
  );
  sky130_fd_sc_hd__xor2_1 _425_ (
    .A(_311_),
    .B(_343_),
    .X(_202_)
  );
  sky130_fd_sc_hd__xor2_1 _426_ (
    .A(_312_),
    .B(_344_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(_202_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a22o_1 _428_ (
    .A1(_310_),
    .A2(_269_),
    .B1(_309_),
    .B2(_270_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2b_1 _429_ (
    .A_N(_310_),
    .B(_342_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__o21ai_0 _430_ (
    .A1(_309_),
    .A2(_270_),
    .B1(_206_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__or4_1 _431_ (
    .A(_202_),
    .B(_203_),
    .C(_205_),
    .D(_207_),
    .X(_208_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _432_ (
    .A(_308_),
    .SLEEP(_340_),
    .X(_209_)
  );
  sky130_fd_sc_hd__nand2b_1 _433_ (
    .A_N(_308_),
    .B(_340_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2b_1 _434_ (
    .A_N(_209_),
    .B(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__xor2_1 _435_ (
    .A(_305_),
    .B(_337_),
    .X(_212_)
  );
  sky130_fd_sc_hd__nor3_1 _436_ (
    .A(_208_),
    .B(_211_),
    .C(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__nor4_1 _437_ (
    .A(_200_),
    .B(_208_),
    .C(_211_),
    .D(_212_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a31oi_1 _438_ (
    .A1(_305_),
    .A2(_271_),
    .A3(_210_),
    .B1(_209_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__maj3_1 _439_ (
    .A(_312_),
    .B(_268_),
    .C(_201_),
    .X(_216_)
  );
  sky130_fd_sc_hd__a31oi_1 _440_ (
    .A1(_204_),
    .A2(_205_),
    .A3(_206_),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _441_ (
    .A1(_208_),
    .A2(_215_),
    .B1(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o21ai_0 _442_ (
    .A1(_214_),
    .A2(_218_),
    .B1(_197_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__maj3_1 _443_ (
    .A(_285_),
    .B(_265_),
    .C(_190_),
    .X(_220_)
  );
  sky130_fd_sc_hd__nor3_1 _444_ (
    .A(_193_),
    .B(_194_),
    .C(_195_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__o21ai_0 _445_ (
    .A1(_220_),
    .A2(_221_),
    .B1(_189_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__maj3_1 _446_ (
    .A(_289_),
    .B(_262_),
    .C(_183_),
    .X(_223_)
  );
  sky130_fd_sc_hd__a21oi_1 _447_ (
    .A1(_186_),
    .A2(_187_),
    .B1(_223_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__a31oi_1 _448_ (
    .A1(_219_),
    .A2(_222_),
    .A3(_224_),
    .B1(_182_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a211oi_1 _449_ (
    .A1(_157_),
    .A2(_158_),
    .B1(_167_),
    .C1(_168_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__o22ai_1 _450_ (
    .A1(_302_),
    .A2(_255_),
    .B1(_160_),
    .B2(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a21oi_1 _451_ (
    .A1(_163_),
    .A2(_227_),
    .B1(_161_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__o21ai_0 _452_ (
    .A1(_166_),
    .A2(_228_),
    .B1(_165_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__nand2b_1 _453_ (
    .A_N(_275_),
    .B(_164_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__maj3_1 _454_ (
    .A(_291_),
    .B(_261_),
    .C(_178_),
    .X(_231_)
  );
  sky130_fd_sc_hd__maj3_1 _455_ (
    .A(_293_),
    .B(_260_),
    .C(_174_),
    .X(_232_)
  );
  sky130_fd_sc_hd__a21oi_1 _456_ (
    .A1(_177_),
    .A2(_231_),
    .B1(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(_156_),
    .B(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__maj3_1 _458_ (
    .A(_257_),
    .B(_330_),
    .C(_278_),
    .X(_235_)
  );
  sky130_fd_sc_hd__o21ai_0 _459_ (
    .A1(_282_),
    .A2(_155_),
    .B1(_235_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__o21ai_0 _460_ (
    .A1(_234_),
    .A2(_236_),
    .B1(_173_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__nand3_1 _461_ (
    .A(_229_),
    .B(_230_),
    .C(_237_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o31a_1 _462_ (
    .A1(_275_),
    .A2(_225_),
    .A3(_238_),
    .B1(_276_),
    .X(_239_)
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(_152_),
    .B(_151_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__nand2_1 _464_ (
    .A(_153_),
    .B(_240_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__o2111ai_1 _465_ (
    .A1(_273_),
    .A2(_315_),
    .B1(_197_),
    .C1(_199_),
    .D1(_213_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(_182_),
    .B(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__nor3_1 _467_ (
    .A(_182_),
    .B(_240_),
    .C(_242_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(_152_),
    .B(_274_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__o21bai_1 _469_ (
    .A1(_243_),
    .A2(_245_),
    .B1_N(_153_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__o22ai_1 _470_ (
    .A1(_239_),
    .A2(_241_),
    .B1(_244_),
    .B2(_246_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__nand3_1 _471_ (
    .A(_153_),
    .B(_239_),
    .C(_245_),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor3_1 _472_ (
    .A(_274_),
    .B(_225_),
    .C(_238_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__o21ai_0 _473_ (
    .A1(_225_),
    .A2(_238_),
    .B1(_274_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__and4b_1 _474_ (
    .A_N(_249_),
    .B(_250_),
    .C(_153_),
    .D(_152_),
    .X(_251_)
  );
  sky130_fd_sc_hd__or3b_1 _475_ (
    .A(_251_),
    .B(_247_),
    .C_N(_248_),
    .X(_154_)
  );
  assign _307_ = r1[31];
  assign _339_ = r2[31];
  assign _306_ = r1[30];
  assign _338_ = r2[30];
  assign _304_ = r1[29];
  assign _336_ = r2[29];
  assign _303_ = r1[28];
  assign _335_ = r2[28];
  assign _302_ = r1[27];
  assign _334_ = r2[27];
  assign _301_ = r1[26];
  assign _333_ = r2[26];
  assign _300_ = r1[25];
  assign _332_ = r2[25];
  assign _299_ = r1[24];
  assign _331_ = r2[24];
  assign _298_ = r1[23];
  assign _330_ = r2[23];
  assign _297_ = r1[22];
  assign _329_ = r2[22];
  assign _296_ = r1[21];
  assign _328_ = r2[21];
  assign _295_ = r1[20];
  assign _327_ = r2[20];
  assign _293_ = r1[19];
  assign _325_ = r2[19];
  assign _292_ = r1[18];
  assign _324_ = r2[18];
  assign _291_ = r1[17];
  assign _323_ = r2[17];
  assign _290_ = r1[16];
  assign _322_ = r2[16];
  assign _289_ = r1[15];
  assign _321_ = r2[15];
  assign _288_ = r1[14];
  assign _320_ = r2[14];
  assign _287_ = r1[13];
  assign _319_ = r2[13];
  assign _286_ = r1[12];
  assign _318_ = r2[12];
  assign _285_ = r1[11];
  assign _317_ = r2[11];
  assign _284_ = r1[10];
  assign _316_ = r2[10];
  assign _314_ = r1[9];
  assign _346_ = r2[9];
  assign _313_ = r1[8];
  assign _345_ = r2[8];
  assign _312_ = r1[7];
  assign _344_ = r2[7];
  assign _311_ = r1[6];
  assign _343_ = r2[6];
  assign _310_ = r1[5];
  assign _342_ = r2[5];
  assign _309_ = r1[4];
  assign _341_ = r2[4];
  assign _308_ = r1[3];
  assign _340_ = r2[3];
  assign _305_ = r1[2];
  assign _337_ = r2[2];
  assign _294_ = r1[1];
  assign _326_ = r2[1];
  assign _283_ = r1[0];
  assign _315_ = r2[0];
  assign _153_ = bCtrl[2];
  assign _152_ = bCtrl[1];
  assign _151_ = bCtrl[0];
  assign bSel = _154_;
endmodule
