/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module controller(f3, f7, opcode, regWR, memWR, wbCtrl, aluOp, aluS1, aluS2, branchCtrl, memCtrl, doJump, doBranch);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  output [3:0] aluOp;
  output aluS1;
  output aluS2;
  output [2:0] branchCtrl;
  output doBranch;
  output doJump;
  input [2:0] f3;
  input [6:0] f7;
  output [2:0] memCtrl;
  output memWR;
  input [6:0] opcode;
  output regWR;
  output [1:0] wbCtrl;
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(opcode[5]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(f3[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2b_1 _39_ (
    .A_N(opcode[6]),
    .B(opcode[4]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nand3b_1 _40_ (
    .A_N(opcode[3]),
    .B(opcode[0]),
    .C(opcode[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand4bb_1 _41_ (
    .A_N(opcode[2]),
    .B_N(opcode[3]),
    .C(opcode[1]),
    .D(opcode[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(_02_),
    .B(_04_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _43_ (
    .A(opcode[5]),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _44_ (
    .A(_06_),
    .Y(aluS2)
  );
  sky130_fd_sc_hd__nand3b_1 _45_ (
    .A_N(opcode[4]),
    .B(opcode[5]),
    .C(opcode[6]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _46_ (
    .A(_04_),
    .B(_07_),
    .Y(doBranch)
  );
  sky130_fd_sc_hd__nand3_1 _47_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .C(opcode[2]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _48_ (
    .A(_07_),
    .B(_08_),
    .Y(doJump)
  );
  sky130_fd_sc_hd__nor2_1 _49_ (
    .A(opcode[6]),
    .B(_04_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3_1 _50_ (
    .A(opcode[4]),
    .B(opcode[6]),
    .C(_04_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor4_1 _51_ (
    .A(opcode[4]),
    .B(_00_),
    .C(opcode[6]),
    .D(_04_),
    .Y(memWR)
  );
  sky130_fd_sc_hd__nor4_1 _52_ (
    .A(opcode[3]),
    .B(opcode[5]),
    .C(_02_),
    .D(_08_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__a211o_1 _53_ (
    .A1(opcode[3]),
    .A2(doJump),
    .B1(_11_),
    .C1(doBranch),
    .X(aluS1)
  );
  sky130_fd_sc_hd__o21ai_0 _54_ (
    .A1(opcode[4]),
    .A2(_00_),
    .B1(_09_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o22ai_1 _55_ (
    .A1(_02_),
    .A2(_03_),
    .B1(_07_),
    .B2(_08_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__clkinv_1 _56_ (
    .A(_13_),
    .Y(wbCtrl[0])
  );
  sky130_fd_sc_hd__nand2_1 _57_ (
    .A(opcode[2]),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(_12_),
    .B(_14_),
    .Y(regWR)
  );
  sky130_fd_sc_hd__or3_1 _59_ (
    .A(f3[0]),
    .B(_04_),
    .C(_07_),
    .X(branchCtrl[0])
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(_01_),
    .B(doBranch),
    .Y(branchCtrl[1])
  );
  sky130_fd_sc_hd__and2_0 _61_ (
    .A(f3[2]),
    .B(doBranch),
    .X(branchCtrl[2])
  );
  sky130_fd_sc_hd__or3_1 _62_ (
    .A(doBranch),
    .B(_10_),
    .C(_13_),
    .X(_15_)
  );
  sky130_fd_sc_hd__nor3_1 _63_ (
    .A(f7[3]),
    .B(f7[5]),
    .C(f7[6]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor4_1 _64_ (
    .A(f7[1]),
    .B(f7[0]),
    .C(f7[2]),
    .D(f7[4]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _65_ (
    .A(_16_),
    .B(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor4_1 _66_ (
    .A(_00_),
    .B(f3[0]),
    .C(f3[1]),
    .D(f3[2]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o21ai_0 _67_ (
    .A1(f3[0]),
    .A2(_18_),
    .B1(_05_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _68_ (
    .A1(_19_),
    .A2(_20_),
    .B1(_15_),
    .Y(aluOp[0])
  );
  sky130_fd_sc_hd__nor4_1 _69_ (
    .A(_01_),
    .B(_02_),
    .C(_04_),
    .D(_18_),
    .Y(aluOp[1])
  );
  sky130_fd_sc_hd__nand2b_1 _70_ (
    .A_N(f3[1]),
    .B(f3[0]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__nand2_1 _71_ (
    .A(f3[2]),
    .B(_05_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _72_ (
    .A1(_18_),
    .A2(_21_),
    .B1(_22_),
    .Y(aluOp[2])
  );
  sky130_fd_sc_hd__nor2_1 _73_ (
    .A(f3[0]),
    .B(f3[2]),
    .Y(_23_)
  );
  sky130_fd_sc_hd__xor2_1 _74_ (
    .A(f3[0]),
    .B(f3[2]),
    .X(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _75_ (
    .A(f3[0]),
    .B(f3[1]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_1 _76_ (
    .A1(f3[0]),
    .A2(f3[1]),
    .B1(f3[2]),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nor2_1 _77_ (
    .A(f3[1]),
    .B(_24_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__mux2i_1 _78_ (
    .A0(_18_),
    .A1(f7[5]),
    .S(_27_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _79_ (
    .A(f3[2]),
    .SLEEP(_21_),
    .X(_29_)
  );
  sky130_fd_sc_hd__nor4bb_1 _80_ (
    .A(f3[1]),
    .B(f7[5]),
    .C_N(f3[2]),
    .D_N(f3[0]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor4_1 _81_ (
    .A(opcode[5]),
    .B(_02_),
    .C(_04_),
    .D(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o21ai_0 _82_ (
    .A1(_18_),
    .A2(_29_),
    .B1(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__o211ai_1 _83_ (
    .A1(_06_),
    .A2(_28_),
    .B1(_32_),
    .C1(_15_),
    .Y(aluOp[3])
  );
  sky130_fd_sc_hd__a21o_1 _84_ (
    .A1(_12_),
    .A2(_14_),
    .B1(doJump),
    .X(wbCtrl[1])
  );
  sky130_fd_sc_hd__nor4_1 _85_ (
    .A(opcode[4]),
    .B(opcode[5]),
    .C(opcode[6]),
    .D(_04_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a32o_1 _86_ (
    .A1(_01_),
    .A2(_24_),
    .A3(_33_),
    .B1(memWR),
    .B2(_23_),
    .X(memCtrl[0])
  );
  sky130_fd_sc_hd__nand2_1 _87_ (
    .A(memWR),
    .B(_26_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o221ai_1 _88_ (
    .A1(f3[1]),
    .A2(f3[2]),
    .B1(_23_),
    .B2(_25_),
    .C1(_33_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o21ai_0 _89_ (
    .A1(_25_),
    .A2(_34_),
    .B1(_35_),
    .Y(memCtrl[1])
  );
  sky130_fd_sc_hd__nand2_1 _90_ (
    .A(_29_),
    .B(_33_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nand2_1 _91_ (
    .A(_34_),
    .B(_36_),
    .Y(memCtrl[2])
  );
endmodule
