/* Generated by Yosys 0.32+66 (git sha1 b168ff99d, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module controller(f3, f7, opcode, regWR, memWR, wbCtrl, aluOp, aluS1, aluS2, branchCtrl, memCtrl, doJump, doBranch);
  wire _0_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _1_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _2_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _3_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _4_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  output [3:0] aluOp;
  wire [3:0] aluOp;
  output aluS1;
  wire aluS1;
  output aluS2;
  wire aluS2;
  output [2:0] branchCtrl;
  wire [2:0] branchCtrl;
  output doBranch;
  wire doBranch;
  output doJump;
  wire doJump;
  input [2:0] f3;
  wire [2:0] f3;
  input [6:0] f7;
  wire [6:0] f7;
  output [2:0] memCtrl;
  wire [2:0] memCtrl;
  output memWR;
  wire memWR;
  input [6:0] opcode;
  wire [6:0] opcode;
  output regWR;
  wire regWR;
  output [1:0] wbCtrl;
  wire [1:0] wbCtrl;
  sky130_fd_sc_hd__nor3_1 _100_ (
    .A(opcode[6]),
    .B(_42_),
    .C(_41_),
    .Y(aluS2)
  );
  sky130_fd_sc_hd__nand4_1 _101_ (
    .A(_31_),
    .B(_36_),
    .C(opcode[6]),
    .D(_37_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__nand2_1 _102_ (
    .A(_43_),
    .B(_35_),
    .Y(doJump)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(opcode[6]),
    .B(_42_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__o221a_2 _104_ (
    .A1(_40_),
    .A2(_37_),
    .B1(_38_),
    .B2(_44_),
    .C1(_36_),
    .X(_45_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(doJump),
    .B(_45_),
    .Y(wbCtrl[0])
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(wbCtrl[0]),
    .B(_14_),
    .Y(regWR)
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(doBranch),
    .B(_22_),
    .Y(branchCtrl[0])
  );
  sky130_fd_sc_hd__nand2_1 _108_ (
    .A(doBranch),
    .B(_16_),
    .Y(branchCtrl[1])
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_19_),
    .B(_32_),
    .Y(branchCtrl[2])
  );
  sky130_fd_sc_hd__nand2_1 _110_ (
    .A(_10_),
    .B(_38_),
    .Y(_46_)
  );
  sky130_fd_sc_hd__nand3_1 _111_ (
    .A(_46_),
    .B(_43_),
    .C(_35_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__o211ai_1 _112_ (
    .A1(_40_),
    .A2(_37_),
    .B1(_36_),
    .C1(_44_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__o21ai_0 _113_ (
    .A1(_13_),
    .A2(_11_),
    .B1(_10_),
    .Y(_49_)
  );
  sky130_fd_sc_hd__nand4_1 _114_ (
    .A(_48_),
    .B(_49_),
    .C(_32_),
    .D(_39_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__nor3_1 _115_ (
    .A(f7[5]),
    .B(f7[4]),
    .C(f7[6]),
    .Y(_51_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(f7[1]),
    .B(f7[0]),
    .Y(_52_)
  );
  sky130_fd_sc_hd__nor2_1 _117_ (
    .A(f7[3]),
    .B(f7[2]),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nand3_1 _118_ (
    .A(_51_),
    .B(_52_),
    .C(_53_),
    .Y(_54_)
  );
  sky130_fd_sc_hd__nor2_1 _119_ (
    .A(f3[0]),
    .B(_54_),
    .Y(_55_)
  );
  sky130_fd_sc_hd__nand3_1 _120_ (
    .A(_19_),
    .B(_22_),
    .C(_16_),
    .Y(_56_)
  );
  sky130_fd_sc_hd__nand3b_1 _121_ (
    .A_N(opcode[6]),
    .B(_30_),
    .C(opcode[4]),
    .Y(_57_)
  );
  sky130_fd_sc_hd__nor2_1 _122_ (
    .A(_57_),
    .B(_41_),
    .Y(_58_)
  );
  sky130_fd_sc_hd__a31oi_1 _123_ (
    .A1(_10_),
    .A2(_56_),
    .A3(_44_),
    .B1(_58_),
    .Y(_59_)
  );
  sky130_fd_sc_hd__o22ai_1 _124_ (
    .A1(_55_),
    .A2(_59_),
    .B1(_47_),
    .B2(_50_),
    .Y(aluOp[0])
  );
  sky130_fd_sc_hd__nand2_1 _125_ (
    .A(_10_),
    .B(_44_),
    .Y(_0_)
  );
  sky130_fd_sc_hd__a211oi_1 _126_ (
    .A1(_46_),
    .A2(_0_),
    .B1(_16_),
    .C1(_54_),
    .Y(aluOp[1])
  );
  sky130_fd_sc_hd__a221oi_1 _127_ (
    .A1(_17_),
    .A2(_54_),
    .B1(_46_),
    .B2(_0_),
    .C1(_19_),
    .Y(aluOp[2])
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(f3[2]),
    .B(f3[0]),
    .Y(_1_)
  );
  sky130_fd_sc_hd__a21oi_1 _129_ (
    .A1(_23_),
    .A2(_1_),
    .B1(f3[1]),
    .Y(_2_)
  );
  sky130_fd_sc_hd__clkinv_1 _130_ (
    .A(f7[5]),
    .Y(_3_)
  );
  sky130_fd_sc_hd__nand2_1 _131_ (
    .A(_23_),
    .B(_1_),
    .Y(_4_)
  );
  sky130_fd_sc_hd__nand3_1 _132_ (
    .A(_4_),
    .B(_16_),
    .C(_3_),
    .Y(_5_)
  );
  sky130_fd_sc_hd__o211ai_1 _133_ (
    .A1(_54_),
    .A2(_2_),
    .B1(aluS2),
    .C1(_5_),
    .Y(_6_)
  );
  sky130_fd_sc_hd__a21oi_1 _134_ (
    .A1(_28_),
    .A2(_3_),
    .B1(_46_),
    .Y(_7_)
  );
  sky130_fd_sc_hd__o21ai_0 _135_ (
    .A1(_28_),
    .A2(_54_),
    .B1(_7_),
    .Y(_8_)
  );
  sky130_fd_sc_hd__o211ai_1 _136_ (
    .A1(_47_),
    .A2(_50_),
    .B1(_6_),
    .C1(_8_),
    .Y(aluOp[3])
  );
  sky130_fd_sc_hd__o21bai_1 _137_ (
    .A1(_15_),
    .A2(_45_),
    .B1_N(doJump),
    .Y(wbCtrl[1])
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(opcode[1]),
    .B(opcode[0]),
    .Y(_9_)
  );
  sky130_fd_sc_hd__nor3_1 _61_ (
    .A(opcode[3]),
    .B(opcode[2]),
    .C(_9_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor3b_1 _62_ (
    .A(opcode[4]),
    .B(opcode[6]),
    .C_N(opcode[5]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _63_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__clkinv_1 _64_ (
    .A(_12_),
    .Y(memWR)
  );
  sky130_fd_sc_hd__nor3_1 _65_ (
    .A(opcode[4]),
    .B(opcode[5]),
    .C(opcode[6]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _66_ (
    .A(_10_),
    .B(_13_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__clkinv_1 _67_ (
    .A(_14_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__clkinv_1 _68_ (
    .A(f3[1]),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nand2_1 _69_ (
    .A(_16_),
    .B(f3[0]),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor2_1 _70_ (
    .A(f3[2]),
    .B(_17_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__clkinv_1 _71_ (
    .A(f3[2]),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nor3_1 _72_ (
    .A(f3[0]),
    .B(f3[1]),
    .C(_19_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _73_ (
    .A1(_18_),
    .A2(_20_),
    .B1(_15_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__clkinv_1 _74_ (
    .A(f3[0]),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand2_1 _75_ (
    .A(_19_),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _76_ (
    .A1(_12_),
    .A2(_23_),
    .B1(_21_),
    .Y(memCtrl[0])
  );
  sky130_fd_sc_hd__nor2_1 _77_ (
    .A(_16_),
    .B(_23_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _78_ (
    .A(_18_),
    .B(_24_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o21ai_0 _79_ (
    .A1(_20_),
    .A2(_24_),
    .B1(_15_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o21ai_0 _80_ (
    .A1(_12_),
    .A2(_25_),
    .B1(_26_),
    .Y(memCtrl[1])
  );
  sky130_fd_sc_hd__o21ai_0 _81_ (
    .A1(_22_),
    .A2(_16_),
    .B1(_19_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nor2_1 _82_ (
    .A(_19_),
    .B(_17_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand2_1 _83_ (
    .A(_15_),
    .B(_28_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__o21ai_0 _84_ (
    .A1(_12_),
    .A2(_27_),
    .B1(_29_),
    .Y(memCtrl[2])
  );
  sky130_fd_sc_hd__clkinv_1 _85_ (
    .A(opcode[5]),
    .Y(_30_)
  );
  sky130_fd_sc_hd__nor2_1 _86_ (
    .A(opcode[4]),
    .B(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nand3_1 _87_ (
    .A(_10_),
    .B(opcode[6]),
    .C(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__clkinv_1 _88_ (
    .A(_32_),
    .Y(doBranch)
  );
  sky130_fd_sc_hd__nand2_1 _89_ (
    .A(opcode[3]),
    .B(opcode[2]),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor2_1 _90_ (
    .A(_9_),
    .B(_33_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nand3_1 _91_ (
    .A(_34_),
    .B(_31_),
    .C(opcode[6]),
    .Y(_35_)
  );
  sky130_fd_sc_hd__clkinv_1 _92_ (
    .A(_9_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__and2b_2 _93_ (
    .A_N(opcode[3]),
    .B(opcode[2]),
    .X(_37_)
  );
  sky130_fd_sc_hd__nor3b_1 _94_ (
    .A(opcode[5]),
    .B(opcode[6]),
    .C_N(opcode[4]),
    .Y(_38_)
  );
  sky130_fd_sc_hd__nand3_1 _95_ (
    .A(_38_),
    .B(_36_),
    .C(_37_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__nand3_1 _96_ (
    .A(_32_),
    .B(_39_),
    .C(_35_),
    .Y(aluS1)
  );
  sky130_fd_sc_hd__nor2_1 _97_ (
    .A(opcode[3]),
    .B(opcode[2]),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nand3_1 _98_ (
    .A(_40_),
    .B(opcode[1]),
    .C(opcode[0]),
    .Y(_41_)
  );
  sky130_fd_sc_hd__nand2_1 _99_ (
    .A(opcode[4]),
    .B(opcode[5]),
    .Y(_42_)
  );
endmodule
