/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module decoder(instIn, opcode, rd, rs1, rs2, fn3, fn7);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  output [2:0] fn3;
  output [6:0] fn7;
  input [31:0] instIn;
  output [6:0] opcode;
  output [4:0] rd;
  output [4:0] rs1;
  output [4:0] rs2;
  sky130_fd_sc_hd__clkinv_1 _129_ (
    .A(_096_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor4bb_1 _130_ (
    .A(_093_),
    .B(_090_),
    .C_N(_079_),
    .D_N(_068_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _131_ (
    .A(_095_),
    .SLEEP(_094_),
    .X(_102_)
  );
  sky130_fd_sc_hd__or3b_1 _132_ (
    .A(_096_),
    .B(_102_),
    .C_N(_101_),
    .X(_103_)
  );
  sky130_fd_sc_hd__and4b_1 _133_ (
    .A_N(_093_),
    .B(_090_),
    .C(_079_),
    .D(_068_),
    .X(_104_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _134_ (
    .A(_094_),
    .SLEEP(_096_),
    .X(_105_)
  );
  sky130_fd_sc_hd__and3b_1 _135_ (
    .A_N(_094_),
    .B(_095_),
    .C(_096_),
    .X(_106_)
  );
  sky130_fd_sc_hd__o21ai_0 _136_ (
    .A1(_105_),
    .A2(_106_),
    .B1(_104_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _137_ (
    .A(_104_),
    .B(_106_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21boi_0 _138_ (
    .A1(_103_),
    .A2(_107_),
    .B1_N(_097_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__a21boi_0 _139_ (
    .A1(_103_),
    .A2(_107_),
    .B1_N(_098_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a21boi_0 _140_ (
    .A1(_103_),
    .A2(_107_),
    .B1_N(_099_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21boi_0 _141_ (
    .A1(_103_),
    .A2(_107_),
    .B1_N(_069_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a21boi_0 _142_ (
    .A1(_103_),
    .A2(_107_),
    .B1_N(_070_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2b_1 _143_ (
    .A_N(_095_),
    .B(_094_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__o21ai_0 _144_ (
    .A1(_100_),
    .A2(_102_),
    .B1(_101_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o211a_1 _145_ (
    .A1(_100_),
    .A2(_102_),
    .B1(_109_),
    .C1(_101_),
    .X(_111_)
  );
  sky130_fd_sc_hd__and2_0 _146_ (
    .A(_080_),
    .B(_111_),
    .X(_124_)
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(_081_),
    .B(_111_),
    .X(_125_)
  );
  sky130_fd_sc_hd__and2_0 _148_ (
    .A(_082_),
    .B(_111_),
    .X(_126_)
  );
  sky130_fd_sc_hd__and2_0 _149_ (
    .A(_083_),
    .B(_111_),
    .X(_127_)
  );
  sky130_fd_sc_hd__and2_0 _150_ (
    .A(_084_),
    .B(_111_),
    .X(_128_)
  );
  sky130_fd_sc_hd__a21boi_0 _151_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_074_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a21boi_0 _152_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_075_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21boi_0 _153_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_076_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a21boi_0 _154_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_077_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21boi_0 _155_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_078_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a21boi_0 _156_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_071_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__a21boi_0 _157_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_072_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a21boi_0 _158_ (
    .A1(_108_),
    .A2(_110_),
    .B1_N(_073_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__and3b_1 _159_ (
    .A_N(_072_),
    .B(_073_),
    .C(_071_),
    .X(_112_)
  );
  sky130_fd_sc_hd__o211ai_1 _160_ (
    .A1(_095_),
    .A2(_112_),
    .B1(_105_),
    .C1(_101_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _161_ (
    .A(_085_),
    .SLEEP(_113_),
    .X(_061_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _162_ (
    .A(_086_),
    .SLEEP(_113_),
    .X(_062_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _163_ (
    .A(_087_),
    .SLEEP(_113_),
    .X(_063_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _164_ (
    .A(_088_),
    .SLEEP(_113_),
    .X(_064_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _165_ (
    .A(_089_),
    .SLEEP(_113_),
    .X(_065_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _166_ (
    .A(_091_),
    .SLEEP(_113_),
    .X(_066_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _167_ (
    .A(_092_),
    .SLEEP(_113_),
    .X(_067_)
  );
  assign opcode = instIn[6:0];
  assign _097_ = instIn[7];
  assign _079_ = instIn[1];
  assign _068_ = instIn[0];
  assign _093_ = instIn[3];
  assign _090_ = instIn[2];
  assign _096_ = instIn[6];
  assign _095_ = instIn[5];
  assign _094_ = instIn[4];
  assign rd[0] = _114_;
  assign _098_ = instIn[8];
  assign rd[1] = _115_;
  assign _099_ = instIn[9];
  assign rd[2] = _116_;
  assign _069_ = instIn[10];
  assign rd[3] = _117_;
  assign _070_ = instIn[11];
  assign rd[4] = _118_;
  assign _080_ = instIn[20];
  assign rs2[0] = _124_;
  assign _081_ = instIn[21];
  assign rs2[1] = _125_;
  assign _082_ = instIn[22];
  assign rs2[2] = _126_;
  assign _083_ = instIn[23];
  assign rs2[3] = _127_;
  assign _084_ = instIn[24];
  assign rs2[4] = _128_;
  assign _074_ = instIn[15];
  assign rs1[0] = _119_;
  assign _075_ = instIn[16];
  assign rs1[1] = _120_;
  assign _076_ = instIn[17];
  assign rs1[2] = _121_;
  assign _077_ = instIn[18];
  assign rs1[3] = _122_;
  assign _078_ = instIn[19];
  assign rs1[4] = _123_;
  assign _071_ = instIn[12];
  assign fn3[0] = _058_;
  assign _072_ = instIn[13];
  assign fn3[1] = _059_;
  assign _073_ = instIn[14];
  assign fn3[2] = _060_;
  assign _085_ = instIn[25];
  assign fn7[0] = _061_;
  assign _086_ = instIn[26];
  assign fn7[1] = _062_;
  assign _087_ = instIn[27];
  assign fn7[2] = _063_;
  assign _088_ = instIn[28];
  assign fn7[3] = _064_;
  assign _089_ = instIn[29];
  assign fn7[4] = _065_;
  assign _091_ = instIn[30];
  assign fn7[5] = _066_;
  assign _092_ = instIn[31];
  assign fn7[6] = _067_;
endmodule
