/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module mux21(a, b, s, y);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  input [31:0] a;
  input [31:0] b;
  input s;
  output [31:0] y;
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(_013_),
    .A1(_045_),
    .S(_064_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _098_ (
    .A0(_014_),
    .A1(_046_),
    .S(_064_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(_015_),
    .A1(_047_),
    .S(_064_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(_016_),
    .A1(_048_),
    .S(_064_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(_017_),
    .A1(_049_),
    .S(_064_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(_018_),
    .A1(_050_),
    .S(_064_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(_019_),
    .A1(_051_),
    .S(_064_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(_020_),
    .A1(_052_),
    .S(_064_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(_021_),
    .A1(_053_),
    .S(_064_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(_023_),
    .A1(_055_),
    .S(_064_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(_024_),
    .A1(_056_),
    .S(_064_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(_000_),
    .A1(_032_),
    .S(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(_011_),
    .A1(_043_),
    .S(_064_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(_022_),
    .A1(_054_),
    .S(_064_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(_025_),
    .A1(_057_),
    .S(_064_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(_026_),
    .A1(_058_),
    .S(_064_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(_027_),
    .A1(_059_),
    .S(_064_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(_028_),
    .A1(_060_),
    .S(_064_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _115_ (
    .A0(_029_),
    .A1(_061_),
    .S(_064_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(_030_),
    .A1(_062_),
    .S(_064_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _117_ (
    .A0(_031_),
    .A1(_063_),
    .S(_064_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _118_ (
    .A0(_001_),
    .A1(_033_),
    .S(_064_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _119_ (
    .A0(_002_),
    .A1(_034_),
    .S(_064_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(_003_),
    .A1(_035_),
    .S(_064_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _121_ (
    .A0(_004_),
    .A1(_036_),
    .S(_064_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _122_ (
    .A0(_005_),
    .A1(_037_),
    .S(_064_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(_006_),
    .A1(_038_),
    .S(_064_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _124_ (
    .A0(_007_),
    .A1(_039_),
    .S(_064_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(_008_),
    .A1(_040_),
    .S(_064_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(_009_),
    .A1(_041_),
    .S(_064_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _127_ (
    .A0(_010_),
    .A1(_042_),
    .S(_064_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _128_ (
    .A0(_012_),
    .A1(_044_),
    .S(_064_),
    .X(_077_)
  );
  assign _013_ = a[21];
  assign _045_ = b[21];
  assign _064_ = s;
  assign y[21] = _078_;
  assign _014_ = a[22];
  assign _046_ = b[22];
  assign y[22] = _079_;
  assign _015_ = a[23];
  assign _047_ = b[23];
  assign y[23] = _080_;
  assign _016_ = a[24];
  assign _048_ = b[24];
  assign y[24] = _081_;
  assign _017_ = a[25];
  assign _049_ = b[25];
  assign y[25] = _082_;
  assign _018_ = a[26];
  assign _050_ = b[26];
  assign y[26] = _083_;
  assign _019_ = a[27];
  assign _051_ = b[27];
  assign y[27] = _084_;
  assign _020_ = a[28];
  assign _052_ = b[28];
  assign y[28] = _085_;
  assign _021_ = a[29];
  assign _053_ = b[29];
  assign y[29] = _086_;
  assign _023_ = a[30];
  assign _055_ = b[30];
  assign y[30] = _088_;
  assign _024_ = a[31];
  assign _056_ = b[31];
  assign y[31] = _089_;
  assign _000_ = a[0];
  assign _032_ = b[0];
  assign y[0] = _065_;
  assign _011_ = a[1];
  assign _043_ = b[1];
  assign y[1] = _076_;
  assign _022_ = a[2];
  assign _054_ = b[2];
  assign y[2] = _087_;
  assign _025_ = a[3];
  assign _057_ = b[3];
  assign y[3] = _090_;
  assign _026_ = a[4];
  assign _058_ = b[4];
  assign y[4] = _091_;
  assign _027_ = a[5];
  assign _059_ = b[5];
  assign y[5] = _092_;
  assign _028_ = a[6];
  assign _060_ = b[6];
  assign y[6] = _093_;
  assign _029_ = a[7];
  assign _061_ = b[7];
  assign y[7] = _094_;
  assign _030_ = a[8];
  assign _062_ = b[8];
  assign y[8] = _095_;
  assign _031_ = a[9];
  assign _063_ = b[9];
  assign y[9] = _096_;
  assign _001_ = a[10];
  assign _033_ = b[10];
  assign y[10] = _066_;
  assign _002_ = a[11];
  assign _034_ = b[11];
  assign y[11] = _067_;
  assign _003_ = a[12];
  assign _035_ = b[12];
  assign y[12] = _068_;
  assign _004_ = a[13];
  assign _036_ = b[13];
  assign y[13] = _069_;
  assign _005_ = a[14];
  assign _037_ = b[14];
  assign y[14] = _070_;
  assign _006_ = a[15];
  assign _038_ = b[15];
  assign y[15] = _071_;
  assign _007_ = a[16];
  assign _039_ = b[16];
  assign y[16] = _072_;
  assign _008_ = a[17];
  assign _040_ = b[17];
  assign y[17] = _073_;
  assign _009_ = a[18];
  assign _041_ = b[18];
  assign y[18] = _074_;
  assign _010_ = a[19];
  assign _042_ = b[19];
  assign y[19] = _075_;
  assign _012_ = a[20];
  assign _044_ = b[20];
  assign y[20] = _077_;
endmodule
