/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module or2(a, b, y);
  input [31:0] a;
  input [31:0] b;
  output [31:0] y;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _00_ (
    .A(b[21]),
    .SLEEP(a[21]),
    .X(y[21])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _01_ (
    .A(b[22]),
    .SLEEP(a[22]),
    .X(y[22])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _02_ (
    .A(b[23]),
    .SLEEP(a[23]),
    .X(y[23])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _03_ (
    .A(b[24]),
    .SLEEP(a[24]),
    .X(y[24])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _04_ (
    .A(b[25]),
    .SLEEP(a[25]),
    .X(y[25])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _05_ (
    .A(b[26]),
    .SLEEP(a[26]),
    .X(y[26])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _06_ (
    .A(b[27]),
    .SLEEP(a[27]),
    .X(y[27])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _07_ (
    .A(b[28]),
    .SLEEP(a[28]),
    .X(y[28])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _08_ (
    .A(b[29]),
    .SLEEP(a[29]),
    .X(y[29])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _09_ (
    .A(b[30]),
    .SLEEP(a[30]),
    .X(y[30])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _10_ (
    .A(b[31]),
    .SLEEP(a[31]),
    .X(y[31])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _11_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(y[0])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _12_ (
    .A(b[1]),
    .SLEEP(a[1]),
    .X(y[1])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _13_ (
    .A(b[2]),
    .SLEEP(a[2]),
    .X(y[2])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _14_ (
    .A(b[3]),
    .SLEEP(a[3]),
    .X(y[3])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _15_ (
    .A(b[4]),
    .SLEEP(a[4]),
    .X(y[4])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _16_ (
    .A(b[5]),
    .SLEEP(a[5]),
    .X(y[5])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _17_ (
    .A(b[6]),
    .SLEEP(a[6]),
    .X(y[6])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _18_ (
    .A(b[7]),
    .SLEEP(a[7]),
    .X(y[7])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _19_ (
    .A(b[8]),
    .SLEEP(a[8]),
    .X(y[8])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _20_ (
    .A(b[9]),
    .SLEEP(a[9]),
    .X(y[9])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _21_ (
    .A(b[10]),
    .SLEEP(a[10]),
    .X(y[10])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _22_ (
    .A(b[11]),
    .SLEEP(a[11]),
    .X(y[11])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _23_ (
    .A(b[12]),
    .SLEEP(a[12]),
    .X(y[12])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _24_ (
    .A(b[13]),
    .SLEEP(a[13]),
    .X(y[13])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _25_ (
    .A(b[14]),
    .SLEEP(a[14]),
    .X(y[14])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _26_ (
    .A(b[15]),
    .SLEEP(a[15]),
    .X(y[15])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _27_ (
    .A(b[16]),
    .SLEEP(a[16]),
    .X(y[16])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _28_ (
    .A(b[17]),
    .SLEEP(a[17]),
    .X(y[17])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _29_ (
    .A(b[18]),
    .SLEEP(a[18]),
    .X(y[18])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _30_ (
    .A(b[19]),
    .SLEEP(a[19]),
    .X(y[19])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _31_ (
    .A(b[20]),
    .SLEEP(a[20]),
    .X(y[20])
  );
endmodule
