/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module signExt(opcode, instIn, immOut);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  output [31:0] immOut;
  input [31:0] instIn;
  input [6:0] opcode;
  sky130_fd_sc_hd__clkinv_1 _229_ (
    .A(_182_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand3b_1 _230_ (
    .A_N(_226_),
    .B(_227_),
    .C(_228_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand4_1 _231_ (
    .A(_223_),
    .B(_222_),
    .C(_224_),
    .D(_225_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(_196_),
    .B(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _233_ (
    .A(_196_),
    .SLEEP(_197_),
    .X(_199_)
  );
  sky130_fd_sc_hd__nand4b_1 _234_ (
    .A_N(_225_),
    .B(_224_),
    .C(_222_),
    .D(_223_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__nor3b_1 _235_ (
    .A(_228_),
    .B(_200_),
    .C_N(_226_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _236_ (
    .A(_198_),
    .SLEEP(_201_),
    .X(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_163_),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand4bb_1 _238_ (
    .A_N(_224_),
    .B_N(_225_),
    .C(_223_),
    .D(_222_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__nor3b_1 _239_ (
    .A(_204_),
    .B(_226_),
    .C_N(_227_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__or3b_1 _240_ (
    .A(_204_),
    .B(_226_),
    .C_N(_227_),
    .X(_206_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_196_),
    .B(_200_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__o32ai_1 _242_ (
    .A1(_227_),
    .A2(_228_),
    .A3(_204_),
    .B1(_200_),
    .B2(_196_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor4_1 _243_ (
    .A(_226_),
    .B(_227_),
    .C(_228_),
    .D(_204_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nor2_1 _244_ (
    .A(_164_),
    .B(_165_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_163_),
    .B(_210_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o31a_1 _246_ (
    .A1(_207_),
    .A2(_209_),
    .A3(_211_),
    .B1(_208_),
    .X(_212_)
  );
  sky130_fd_sc_hd__o31ai_1 _247_ (
    .A1(_207_),
    .A2(_209_),
    .A3(_211_),
    .B1(_208_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__o21ai_0 _248_ (
    .A1(_205_),
    .A2(_212_),
    .B1(_182_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(_203_),
    .B(_214_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _250_ (
    .A(_164_),
    .B(_202_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_214_),
    .B(_215_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(_165_),
    .B(_202_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand2_1 _253_ (
    .A(_214_),
    .B(_216_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_166_),
    .B(_202_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(_214_),
    .B(_217_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _256_ (
    .A(_167_),
    .B(_202_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_214_),
    .B(_218_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(_168_),
    .B(_202_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__nand2_1 _259_ (
    .A(_214_),
    .B(_219_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(_169_),
    .B(_202_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(_214_),
    .B(_220_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _262_ (
    .A(_170_),
    .B(_202_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_214_),
    .B(_221_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__nand3_1 _264_ (
    .A(_199_),
    .B(_206_),
    .C(_213_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a31oi_1 _265_ (
    .A1(_199_),
    .A2(_206_),
    .A3(_213_),
    .B1(_195_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__a21o_1 _266_ (
    .A1(_171_),
    .A2(_201_),
    .B1(_187_),
    .X(_141_)
  );
  sky130_fd_sc_hd__a21o_1 _267_ (
    .A1(_172_),
    .A2(_201_),
    .B1(_187_),
    .X(_142_)
  );
  sky130_fd_sc_hd__a21o_1 _268_ (
    .A1(_173_),
    .A2(_201_),
    .B1(_187_),
    .X(_143_)
  );
  sky130_fd_sc_hd__a21o_1 _269_ (
    .A1(_174_),
    .A2(_201_),
    .B1(_187_),
    .X(_144_)
  );
  sky130_fd_sc_hd__a21o_1 _270_ (
    .A1(_175_),
    .A2(_201_),
    .B1(_187_),
    .X(_145_)
  );
  sky130_fd_sc_hd__a21o_1 _271_ (
    .A1(_176_),
    .A2(_201_),
    .B1(_187_),
    .X(_146_)
  );
  sky130_fd_sc_hd__a21o_1 _272_ (
    .A1(_177_),
    .A2(_201_),
    .B1(_187_),
    .X(_147_)
  );
  sky130_fd_sc_hd__a21o_1 _273_ (
    .A1(_178_),
    .A2(_201_),
    .B1(_187_),
    .X(_148_)
  );
  sky130_fd_sc_hd__a21o_1 _274_ (
    .A1(_179_),
    .A2(_201_),
    .B1(_187_),
    .X(_149_)
  );
  sky130_fd_sc_hd__a21o_1 _275_ (
    .A1(_180_),
    .A2(_201_),
    .B1(_187_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a21o_1 _276_ (
    .A1(_181_),
    .A2(_201_),
    .B1(_187_),
    .X(_152_)
  );
  sky130_fd_sc_hd__nor3_1 _277_ (
    .A(_202_),
    .B(_205_),
    .C(_212_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _278_ (
    .A(_195_),
    .B(_188_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _279_ (
    .A(_228_),
    .B(_206_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a22o_1 _280_ (
    .A1(_171_),
    .A2(_208_),
    .B1(_189_),
    .B2(_183_),
    .X(_129_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _281_ (
    .A(_198_),
    .SLEEP(_208_),
    .X(_190_)
  );
  sky130_fd_sc_hd__a22o_1 _282_ (
    .A1(_184_),
    .A2(_205_),
    .B1(_190_),
    .B2(_172_),
    .X(_140_)
  );
  sky130_fd_sc_hd__a22o_1 _283_ (
    .A1(_185_),
    .A2(_205_),
    .B1(_190_),
    .B2(_173_),
    .X(_151_)
  );
  sky130_fd_sc_hd__a22o_1 _284_ (
    .A1(_161_),
    .A2(_205_),
    .B1(_190_),
    .B2(_174_),
    .X(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _285_ (
    .A1(_162_),
    .A2(_205_),
    .B1(_190_),
    .B2(_175_),
    .X(_155_)
  );
  sky130_fd_sc_hd__and2_0 _286_ (
    .A(_176_),
    .B(_186_),
    .X(_156_)
  );
  sky130_fd_sc_hd__and2_0 _287_ (
    .A(_177_),
    .B(_186_),
    .X(_157_)
  );
  sky130_fd_sc_hd__and2_0 _288_ (
    .A(_178_),
    .B(_186_),
    .X(_158_)
  );
  sky130_fd_sc_hd__and2_0 _289_ (
    .A(_179_),
    .B(_186_),
    .X(_159_)
  );
  sky130_fd_sc_hd__and2_0 _290_ (
    .A(_180_),
    .B(_186_),
    .X(_160_)
  );
  sky130_fd_sc_hd__and2_0 _291_ (
    .A(_181_),
    .B(_186_),
    .X(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _292_ (
    .A1(_212_),
    .A2(_189_),
    .B1(_182_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nor2_1 _293_ (
    .A(_196_),
    .B(_204_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(_183_),
    .B(_192_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _295_ (
    .A(_164_),
    .B(_198_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nand3_1 _296_ (
    .A(_191_),
    .B(_193_),
    .C(_194_),
    .Y(_131_)
  );
  assign _223_ = opcode[1];
  assign _222_ = opcode[0];
  assign _224_ = opcode[2];
  assign _225_ = opcode[3];
  assign _226_ = opcode[4];
  assign _227_ = opcode[5];
  assign _228_ = opcode[6];
  assign _163_ = instIn[12];
  assign _164_ = instIn[13];
  assign _165_ = instIn[14];
  assign _182_ = instIn[31];
  assign immOut[12] = _132_;
  assign immOut[13] = _133_;
  assign immOut[14] = _134_;
  assign _166_ = instIn[15];
  assign immOut[15] = _135_;
  assign _167_ = instIn[16];
  assign immOut[16] = _136_;
  assign _168_ = instIn[17];
  assign immOut[17] = _137_;
  assign _169_ = instIn[18];
  assign immOut[18] = _138_;
  assign _170_ = instIn[19];
  assign immOut[19] = _139_;
  assign _171_ = instIn[20];
  assign immOut[20] = _141_;
  assign _172_ = instIn[21];
  assign immOut[21] = _142_;
  assign _173_ = instIn[22];
  assign immOut[22] = _143_;
  assign _174_ = instIn[23];
  assign immOut[23] = _144_;
  assign _175_ = instIn[24];
  assign immOut[24] = _145_;
  assign _176_ = instIn[25];
  assign immOut[25] = _146_;
  assign _177_ = instIn[26];
  assign immOut[26] = _147_;
  assign _178_ = instIn[27];
  assign immOut[27] = _148_;
  assign _179_ = instIn[28];
  assign immOut[28] = _149_;
  assign _180_ = instIn[29];
  assign immOut[29] = _150_;
  assign _181_ = instIn[30];
  assign immOut[30] = _152_;
  assign immOut[31] = _153_;
  assign _183_ = instIn[7];
  assign immOut[0] = _129_;
  assign _184_ = instIn[8];
  assign immOut[1] = _140_;
  assign _185_ = instIn[9];
  assign immOut[2] = _151_;
  assign _161_ = instIn[10];
  assign immOut[3] = _154_;
  assign _162_ = instIn[11];
  assign immOut[4] = _155_;
  assign immOut[5] = _156_;
  assign immOut[6] = _157_;
  assign immOut[7] = _158_;
  assign immOut[8] = _159_;
  assign immOut[9] = _160_;
  assign immOut[10] = _130_;
  assign immOut[11] = _131_;
endmodule
